"""initial schema

Revision ID: b4b696a3f8da
Revises: 
Create Date: 2026-09-19 08:51:01.935661
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b4b696a3f8da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cpses'))
    )
    op.create_index(op.f('ix_cpses_code'), 'cpses', ['code'], unique=True)
    op.create_table('engine_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('embedding_backend', sa.String(length=32), nullable=False),
    sa.Column('embedding_model', sa.String(length=160), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('vector_index', sa.String(length=32), nullable=False),
    sa.Column('fuzzy_backend', sa.String(length=32), nullable=False),
    sa.Column('llm_extraction', sa.String(length=64), nullable=True),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('candidate_pairs', sa.Integer(), nullable=True),
    sa.Column('all_pairs', sa.Integer(), nullable=True),
    sa.Column('reduction_ratio', sa.Float(), nullable=True),
    sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engine_runs'))
    )
    op.create_index(op.f('ix_engine_runs_split'), 'engine_runs', ['split'], unique=False)
    op.create_table('standard_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('retrieved_at', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_sources'))
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpse_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sap_plant_code', sa.String(length=8), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpse_id'], ['cpses.id'], name=op.f('fk_plants_cpse_id_cpses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants')),
    sa.UniqueConstraint('cpse_id', 'name', name='uq_plants_cpse_id')
    )
    op.create_index('ix_plants_cpse_code', 'plants', ['cpse_id', 'sap_plant_code'], unique=False)
    op.create_index(op.f('ix_plants_cpse_id'), 'plants', ['cpse_id'], unique=False)
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('body', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('family', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['standard_sources.id'], name=op.f('fk_standards_source_id_standard_sources')),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['standards.id'], name=op.f('fk_standards_superseded_by_id_standards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standards'))
    )
    op.create_index(op.f('ix_standards_code'), 'standards', ['code'], unique=True)
    op.create_index(op.f('ix_standards_family'), 'standards', ['family'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('cpse_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpse_id'], ['cpses.id'], name=op.f('fk_users_cpse_id_cpses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('record_a_id', sa.Integer(), nullable=True),
    sa.Column('record_b_id', sa.Integer(), nullable=True),
    sa.Column('score_at_event', sa.Float(), nullable=True),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_at'), 'audit_events', ['at'], unique=False)
    op.create_index('ix_audit_events_at_action', 'audit_events', ['at', 'action'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_table('material_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=False),
    sa.Column('cpse_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('legacy_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('normalised_description', sa.Text(), nullable=True),
    sa.Column('uom', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('block_bucket', sa.String(length=80), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('unit_value', sa.Float(), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('recipe', sa.String(length=120), nullable=True),
    sa.Column('attrs_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpse_id'], ['cpses.id'], name=op.f('fk_material_records_cpse_id_cpses')),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_material_records_plant_id_plants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_records'))
    )
    op.create_index(op.f('ix_material_records_category'), 'material_records', ['category'], unique=False)
    op.create_index(op.f('ix_material_records_cluster_id'), 'material_records', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_material_records_cpse_id'), 'material_records', ['cpse_id'], unique=False)
    op.create_index('ix_material_records_cpse_legacy', 'material_records', ['cpse_id', 'legacy_code'], unique=False)
    op.create_index(op.f('ix_material_records_legacy_code'), 'material_records', ['legacy_code'], unique=False)
    op.create_index('ix_material_records_plant', 'material_records', ['plant_id'], unique=False)
    op.create_index(op.f('ix_material_records_source_record_id'), 'material_records', ['source_record_id'], unique=True)
    op.create_index(op.f('ix_material_records_split'), 'material_records', ['split'], unique=False)
    op.create_index('ix_material_records_split_category', 'material_records', ['split', 'category'], unique=False)
    op.create_table('sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_expiry', 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('standard_designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=False),
    sa.Column('normalised', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_standard_designations_standard_id_standards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_designations')),
    sa.UniqueConstraint('designation', name='uq_standard_designations_designation')
    )
    op.create_index(op.f('ix_standard_designations_designation'), 'standard_designations', ['designation'], unique=False)
    op.create_index(op.f('ix_standard_designations_normalised'), 'standard_designations', ['normalised'], unique=False)
    op.create_index(op.f('ix_standard_designations_standard_id'), 'standard_designations', ['standard_id'], unique=False)
    op.create_table('standard_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_standard_id', sa.Integer(), nullable=False),
    sa.Column('target_standard_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=24), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('verification', sa.String(length=24), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scoped_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relationship IN ('EQUIVALENT','SUPERSET','SUBSTITUTE','CONFLICT','RELATED')", name=op.f('ck_standard_relationships_relationship_known')),
    sa.CheckConstraint("verification <> 'VERIFIED' OR source_id IS NOT NULL", name=op.f('ck_standard_relationships_verified_needs_source')),
    sa.CheckConstraint("verification IN ('VERIFIED','SCOPED','REQUIRES_REVIEW','UNVERIFIED')", name=op.f('ck_standard_relationships_verification_known')),
    sa.CheckConstraint('source_standard_id <> target_standard_id', name=op.f('ck_standard_relationships_no_self_edge')),
    sa.ForeignKeyConstraint(['source_id'], ['standard_sources.id'], name=op.f('fk_standard_relationships_source_id_standard_sources')),
    sa.ForeignKeyConstraint(['source_standard_id'], ['standards.id'], name=op.f('fk_standard_relationships_source_standard_id_standards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_standard_id'], ['standards.id'], name=op.f('fk_standard_relationships_target_standard_id_standards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_relationships')),
    sa.UniqueConstraint('source_standard_id', 'target_standard_id', 'relationship', name='uq_standard_relationships_source_standard_id')
    )
    op.create_index('ix_standard_relationships_pair', 'standard_relationships', ['source_standard_id', 'target_standard_id'], unique=False)
    op.create_index(op.f('ix_standard_relationships_source_standard_id'), 'standard_relationships', ['source_standard_id'], unique=False)
    op.create_index(op.f('ix_standard_relationships_target_standard_id'), 'standard_relationships', ['target_standard_id'], unique=False)
    op.create_table('standard_text_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('embedded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['standard_sources.id'], name=op.f('fk_standard_text_chunks_source_id_standard_sources')),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_standard_text_chunks_standard_id_standards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_text_chunks'))
    )
    op.create_index(op.f('ix_standard_text_chunks_standard_id'), 'standard_text_chunks', ['standard_id'], unique=False)
    op.create_index('ix_standard_text_chunks_std_seq', 'standard_text_chunks', ['standard_id', 'seq'], unique=False)
    op.create_table('material_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.Column('is_hard_key', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('RULE','LLM','STEWARD','ERP')", name=op.f('ck_material_attributes_source_known')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_material_attributes_confidence_range')),
    sa.ForeignKeyConstraint(['record_id'], ['material_records.id'], name=op.f('fk_material_attributes_record_id_material_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_attributes')),
    sa.UniqueConstraint('record_id', 'key', name='uq_material_attributes_record_id')
    )
    op.create_index('ix_material_attributes_key_value', 'material_attributes', ['key', 'value'], unique=False)
    op.create_index(op.f('ix_material_attributes_record_id'), 'material_attributes', ['record_id'], unique=False)
    op.create_table('material_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_record_id', sa.Integer(), nullable=True),
    sa.Column('canonical_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('equivalence_status', sa.String(length=16), nullable=False),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_record_id'], ['material_records.id'], name=op.f('fk_material_identities_canonical_record_id_material_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_identities'))
    )
    op.create_index(op.f('ix_material_identities_category'), 'material_identities', ['category'], unique=False)
    op.create_table('material_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_a_id', sa.Integer(), nullable=False),
    sa.Column('record_b_id', sa.Integer(), nullable=False),
    sa.Column('cosine', sa.Float(), nullable=False),
    sa.Column('fuzzy', sa.Float(), nullable=False),
    sa.Column('attribute_agreement', sa.Float(), nullable=True),
    sa.Column('coverage', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_without_veto', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('equivalence_status', sa.String(length=16), nullable=False),
    sa.Column('vetoed', sa.Boolean(), nullable=False),
    sa.Column('capped_by_coverage', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope', sa.String(length=12), nullable=True),
    sa.Column('same_plant', sa.Boolean(), nullable=False),
    sa.Column('priority_uncertainty', sa.Float(), nullable=True),
    sa.Column('priority_thin_evidence', sa.Float(), nullable=True),
    sa.Column('priority_value_at_stake', sa.Float(), nullable=True),
    sa.Column('priority_total', sa.Float(), nullable=True),
    sa.Column('priority_band', sa.String(length=12), nullable=True),
    sa.Column('engine_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('AUTO_SUGGEST','REVIEW','DISCARD','REJECTED_VETO')", name=op.f('ck_material_matches_decision_known')),
    sa.CheckConstraint("equivalence_status IN ('IDENTICAL','EQUIVALENT','CONDITIONAL','DIFFERENT','CONFLICT','UNRESOLVED')", name=op.f('ck_material_matches_equivalence_known')),
    sa.CheckConstraint('record_a_id < record_b_id', name=op.f('ck_material_matches_ordered_pair')),
    sa.ForeignKeyConstraint(['engine_run_id'], ['engine_runs.id'], name=op.f('fk_material_matches_engine_run_id_engine_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_a_id'], ['material_records.id'], name=op.f('fk_material_matches_record_a_id_material_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_b_id'], ['material_records.id'], name=op.f('fk_material_matches_record_b_id_material_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_matches')),
    sa.UniqueConstraint('record_a_id', 'record_b_id', name='uq_material_matches_record_a_id')
    )
    op.create_index(op.f('ix_material_matches_decision'), 'material_matches', ['decision'], unique=False)
    op.create_index('ix_material_matches_decision_score', 'material_matches', ['decision', 'score'], unique=False)
    op.create_index(op.f('ix_material_matches_engine_run_id'), 'material_matches', ['engine_run_id'], unique=False)
    op.create_index('ix_material_matches_priority', 'material_matches', ['priority_band', 'priority_total'], unique=False)
    op.create_index(op.f('ix_material_matches_priority_band'), 'material_matches', ['priority_band'], unique=False)
    op.create_index(op.f('ix_material_matches_record_a_id'), 'material_matches', ['record_a_id'], unique=False)
    op.create_index(op.f('ix_material_matches_record_b_id'), 'material_matches', ['record_b_id'], unique=False)
    op.create_index('ix_material_matches_scope', 'material_matches', ['scope'], unique=False)
    op.create_index(op.f('ix_material_matches_score'), 'material_matches', ['score'], unique=False)
    op.create_index(op.f('ix_material_matches_vetoed'), 'material_matches', ['vetoed'], unique=False)
    op.create_table('code_refusals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('group_key', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['material_identities.id'], name=op.f('fk_code_refusals_identity_id_material_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_refusals'))
    )
    op.create_index(op.f('ix_code_refusals_group_key'), 'code_refusals', ['group_key'], unique=False)
    op.create_table('identity_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['material_identities.id'], name=op.f('fk_identity_members_identity_id_material_identities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['material_records.id'], name=op.f('fk_identity_members_record_id_material_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_members')),
    sa.UniqueConstraint('identity_id', 'record_id', name='uq_identity_members_identity_id')
    )
    op.create_index(op.f('ix_identity_members_identity_id'), 'identity_members', ['identity_id'], unique=False)
    op.create_index(op.f('ix_identity_members_record_id'), 'identity_members', ['record_id'], unique=False)
    op.create_table('impact_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('participating_cpse_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('demand_multiplier', sa.Float(), nullable=False),
    sa.Column('required_qty', sa.Float(), nullable=False),
    sa.Column('combined_stock', sa.Float(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('surplus', sa.Float(), nullable=False),
    sa.Column('procurement_requirement', sa.Float(), nullable=False),
    sa.Column('legacy_codes_consolidated', sa.Integer(), nullable=False),
    sa.Column('aggregation_opportunity', sa.Boolean(), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provenance IN ('MEASURED','DERIVED','SIMULATED')", name=op.f('ck_impact_scenarios_provenance_known')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_impact_scenarios_created_by_id_users')),
    sa.ForeignKeyConstraint(['identity_id'], ['material_identities.id'], name=op.f('fk_impact_scenarios_identity_id_material_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_scenarios'))
    )
    op.create_index(op.f('ix_impact_scenarios_identity_id'), 'impact_scenarios', ['identity_id'], unique=False)
    op.create_table('match_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('value_a', sa.String(length=80), nullable=True),
    sa.Column('value_b', sa.String(length=80), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('is_hard_key', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict IN ('MATCH','MISMATCH','UNKNOWN','REVIEW_SCOPE')", name=op.f('ck_match_evidence_verdict_known')),
    sa.ForeignKeyConstraint(['match_id'], ['material_matches.id'], name=op.f('fk_match_evidence_match_id_material_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_evidence')),
    sa.UniqueConstraint('match_id', 'key', name='uq_match_evidence_match_id')
    )
    op.create_index(op.f('ix_match_evidence_match_id'), 'match_evidence', ['match_id'], unique=False)
    op.create_table('national_material_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nmc', sa.String(length=64), nullable=False),
    sa.Column('class_code', sa.String(length=24), nullable=False),
    sa.Column('serial', sa.Integer(), nullable=False),
    sa.Column('check_digit', sa.Integer(), nullable=True),
    sa.Column('segment_name', sa.String(length=120), nullable=True),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('class_name', sa.String(length=120), nullable=True),
    sa.Column('canonical_description', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(length=300), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'SUPERSEDED' OR superseded_by_id IS NOT NULL", name=op.f('ck_national_material_codes_superseded_needs_target')),
    sa.CheckConstraint("status IN ('ACTIVE','SUPERSEDED','REVOKED')", name=op.f('ck_national_material_codes_status_known')),
    sa.ForeignKeyConstraint(['identity_id'], ['material_identities.id'], name=op.f('fk_national_material_codes_identity_id_material_identities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_national_material_codes_issued_by_id_users')),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['national_material_codes.id'], name=op.f('fk_national_material_codes_superseded_by_id_national_material_codes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_national_material_codes')),
    sa.UniqueConstraint('class_code', 'serial', name='uq_national_material_codes_class_code')
    )
    op.create_index(op.f('ix_national_material_codes_class_code'), 'national_material_codes', ['class_code'], unique=False)
    op.create_index(op.f('ix_national_material_codes_identity_id'), 'national_material_codes', ['identity_id'], unique=False)
    op.create_index(op.f('ix_national_material_codes_nmc'), 'national_material_codes', ['nmc'], unique=True)
    op.create_index(op.f('ix_national_material_codes_status'), 'national_material_codes', ['status'], unique=False)
    op.create_index('ix_nmc_class_status', 'national_material_codes', ['class_code', 'status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('score_at_decision', sa.Float(), nullable=True),
    sa.Column('value_at_stake', sa.Float(), nullable=False),
    sa.Column('second_by_id', sa.Integer(), nullable=True),
    sa.Column('second_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('approve','reject','conditional')", name=op.f('ck_reviews_action_known')),
    sa.CheckConstraint("status IN ('applied','awaiting_second','withdrawn')", name=op.f('ck_reviews_status_known')),
    sa.CheckConstraint('second_by_id IS NULL OR second_by_id <> decided_by_id', name=op.f('ck_reviews_no_self_countersign')),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_reviews_decided_by_id_users')),
    sa.ForeignKeyConstraint(['match_id'], ['material_matches.id'], name=op.f('fk_reviews_match_id_material_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_by_id'], ['users.id'], name=op.f('fk_reviews_second_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('match_id', name='uq_reviews_match_id')
    )
    op.create_index(op.f('ix_reviews_action'), 'reviews', ['action'], unique=False)
    op.create_index(op.f('ix_reviews_decided_by_id'), 'reviews', ['decided_by_id'], unique=False)
    op.create_index(op.f('ix_reviews_match_id'), 'reviews', ['match_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index('ix_reviews_status_value', 'reviews', ['status', 'value_at_stake'], unique=False)
    op.create_table('standard_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_from_llm', sa.Boolean(), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['standard_text_chunks.id'], name=op.f('fk_standard_evidence_chunk_id_standard_text_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['material_matches.id'], name=op.f('fk_standard_evidence_match_id_material_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['standard_relationships.id'], name=op.f('fk_standard_evidence_relationship_id_standard_relationships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_evidence'))
    )
    op.create_index(op.f('ix_standard_evidence_match_id'), 'standard_evidence', ['match_id'], unique=False)
    op.create_table('workflow_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_ref', sa.String(length=40), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('assigned_steward_id', sa.Integer(), nullable=True),
    sa.Column('assigned_engineer_id', sa.Integer(), nullable=True),
    sa.Column('procurement_state', sa.String(length=40), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('AI','DATA_STEWARD','ENGINEERING','PROCUREMENT','FINAL_GOVERNANCE')", name=op.f('ck_workflow_cases_stage_known')),
    sa.ForeignKeyConstraint(['assigned_engineer_id'], ['users.id'], name=op.f('fk_workflow_cases_assigned_engineer_id_users')),
    sa.ForeignKeyConstraint(['assigned_steward_id'], ['users.id'], name=op.f('fk_workflow_cases_assigned_steward_id_users')),
    sa.ForeignKeyConstraint(['match_id'], ['material_matches.id'], name=op.f('fk_workflow_cases_match_id_material_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_cases')),
    sa.UniqueConstraint('match_id', name='uq_workflow_cases_match_id')
    )
    op.create_index(op.f('ix_workflow_cases_case_ref'), 'workflow_cases', ['case_ref'], unique=True)
    op.create_index(op.f('ix_workflow_cases_match_id'), 'workflow_cases', ['match_id'], unique=False)
    op.create_index(op.f('ix_workflow_cases_stage'), 'workflow_cases', ['stage'], unique=False)
    op.create_index('ix_workflow_cases_stage_state', 'workflow_cases', ['stage', 'state'], unique=False)
    op.create_index(op.f('ix_workflow_cases_state'), 'workflow_cases', ['state'], unique=False)
    op.create_table('code_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('link_status', sa.String(length=16), nullable=False),
    sa.Column('unknown_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("link_status IN ('CONFIRMED','PROVISIONAL','WITHDRAWN')", name=op.f('ck_code_members_link_status_known')),
    sa.ForeignKeyConstraint(['code_id'], ['national_material_codes.id'], name=op.f('fk_code_members_code_id_national_material_codes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], name=op.f('fk_code_members_confirmed_by_id_users')),
    sa.ForeignKeyConstraint(['record_id'], ['material_records.id'], name=op.f('fk_code_members_record_id_material_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_members')),
    sa.UniqueConstraint('code_id', 'record_id', name='uq_code_members_code_id')
    )
    op.create_index(op.f('ix_code_members_code_id'), 'code_members', ['code_id'], unique=False)
    op.create_index('ix_code_members_record', 'code_members', ['record_id'], unique=False)
    op.create_index(op.f('ix_code_members_record_id'), 'code_members', ['record_id'], unique=False)
    op.create_table('procurement_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('requesting_cpse_id', sa.Integer(), nullable=False),
    sa.Column('required_qty', sa.Float(), nullable=False),
    sa.Column('available_qty', sa.Float(), nullable=False),
    sa.Column('best_source_record_id', sa.Integer(), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('signal', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=12), nullable=True),
    sa.Column('standards_status', sa.String(length=32), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=True),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provenance IN ('MEASURED','DERIVED','SIMULATED')", name=op.f('ck_procurement_opportunities_provenance_known')),
    sa.CheckConstraint("signal IN ('CROSS_CPSE_STOCK_FOUND','DEMAND_AGGREGATION_CANDIDATE','OPPORTUNITY_DETECTED','NO_CROSS_CPSE_STOCK','UNRESOLVED_CASE')", name=op.f('ck_procurement_opportunities_signal_known')),
    sa.CheckConstraint('coverage >= 0 AND coverage <= 1', name=op.f('ck_procurement_opportunities_coverage_range')),
    sa.ForeignKeyConstraint(['best_source_record_id'], ['material_records.id'], name=op.f('fk_procurement_opportunities_best_source_record_id_material_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['code_id'], ['national_material_codes.id'], name=op.f('fk_procurement_opportunities_code_id_national_material_codes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['material_identities.id'], name=op.f('fk_procurement_opportunities_identity_id_material_identities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requesting_cpse_id'], ['cpses.id'], name=op.f('fk_procurement_opportunities_requesting_cpse_id_cpses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_opportunities'))
    )
    op.create_index('ix_proc_signal_coverage', 'procurement_opportunities', ['signal', 'coverage'], unique=False)
    op.create_index(op.f('ix_procurement_opportunities_identity_id'), 'procurement_opportunities', ['identity_id'], unique=False)
    op.create_index(op.f('ix_procurement_opportunities_requesting_cpse_id'), 'procurement_opportunities', ['requesting_cpse_id'], unique=False)
    op.create_index(op.f('ix_procurement_opportunities_signal'), 'procurement_opportunities', ['signal'], unique=False)
    op.create_table('workflow_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_workflow_comments_author_id_users')),
    sa.ForeignKeyConstraint(['case_id'], ['workflow_cases.id'], name=op.f('fk_workflow_comments_case_id_workflow_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_comments'))
    )
    op.create_index(op.f('ix_workflow_comments_case_id'), 'workflow_comments', ['case_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('from_stage', sa.String(length=24), nullable=True),
    sa.Column('to_stage', sa.String(length=24), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_workflow_events_actor_id_users')),
    sa.ForeignKeyConstraint(['case_id'], ['workflow_cases.id'], name=op.f('fk_workflow_events_case_id_workflow_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_events'))
    )
    op.create_index(op.f('ix_workflow_events_at'), 'workflow_events', ['at'], unique=False)
    op.create_index(op.f('ix_workflow_events_case_id'), 'workflow_events', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_events_case_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_at'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_workflow_comments_case_id'), table_name='workflow_comments')
    op.drop_table('workflow_comments')
    op.drop_index(op.f('ix_procurement_opportunities_signal'), table_name='procurement_opportunities')
    op.drop_index(op.f('ix_procurement_opportunities_requesting_cpse_id'), table_name='procurement_opportunities')
    op.drop_index(op.f('ix_procurement_opportunities_identity_id'), table_name='procurement_opportunities')
    op.drop_index('ix_proc_signal_coverage', table_name='procurement_opportunities')
    op.drop_table('procurement_opportunities')
    op.drop_index(op.f('ix_code_members_record_id'), table_name='code_members')
    op.drop_index('ix_code_members_record', table_name='code_members')
    op.drop_index(op.f('ix_code_members_code_id'), table_name='code_members')
    op.drop_table('code_members')
    op.drop_index(op.f('ix_workflow_cases_state'), table_name='workflow_cases')
    op.drop_index('ix_workflow_cases_stage_state', table_name='workflow_cases')
    op.drop_index(op.f('ix_workflow_cases_stage'), table_name='workflow_cases')
    op.drop_index(op.f('ix_workflow_cases_match_id'), table_name='workflow_cases')
    op.drop_index(op.f('ix_workflow_cases_case_ref'), table_name='workflow_cases')
    op.drop_table('workflow_cases')
    op.drop_index(op.f('ix_standard_evidence_match_id'), table_name='standard_evidence')
    op.drop_table('standard_evidence')
    op.drop_index('ix_reviews_status_value', table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_match_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_decided_by_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_action'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_nmc_class_status', table_name='national_material_codes')
    op.drop_index(op.f('ix_national_material_codes_status'), table_name='national_material_codes')
    op.drop_index(op.f('ix_national_material_codes_nmc'), table_name='national_material_codes')
    op.drop_index(op.f('ix_national_material_codes_identity_id'), table_name='national_material_codes')
    op.drop_index(op.f('ix_national_material_codes_class_code'), table_name='national_material_codes')
    op.drop_table('national_material_codes')
    op.drop_index(op.f('ix_match_evidence_match_id'), table_name='match_evidence')
    op.drop_table('match_evidence')
    op.drop_index(op.f('ix_impact_scenarios_identity_id'), table_name='impact_scenarios')
    op.drop_table('impact_scenarios')
    op.drop_index(op.f('ix_identity_members_record_id'), table_name='identity_members')
    op.drop_index(op.f('ix_identity_members_identity_id'), table_name='identity_members')
    op.drop_table('identity_members')
    op.drop_index(op.f('ix_code_refusals_group_key'), table_name='code_refusals')
    op.drop_table('code_refusals')
    op.drop_index(op.f('ix_material_matches_vetoed'), table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_score'), table_name='material_matches')
    op.drop_index('ix_material_matches_scope', table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_record_b_id'), table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_record_a_id'), table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_priority_band'), table_name='material_matches')
    op.drop_index('ix_material_matches_priority', table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_engine_run_id'), table_name='material_matches')
    op.drop_index('ix_material_matches_decision_score', table_name='material_matches')
    op.drop_index(op.f('ix_material_matches_decision'), table_name='material_matches')
    op.drop_table('material_matches')
    op.drop_index(op.f('ix_material_identities_category'), table_name='material_identities')
    op.drop_table('material_identities')
    op.drop_index(op.f('ix_material_attributes_record_id'), table_name='material_attributes')
    op.drop_index('ix_material_attributes_key_value', table_name='material_attributes')
    op.drop_table('material_attributes')
    op.drop_index('ix_standard_text_chunks_std_seq', table_name='standard_text_chunks')
    op.drop_index(op.f('ix_standard_text_chunks_standard_id'), table_name='standard_text_chunks')
    op.drop_table('standard_text_chunks')
    op.drop_index(op.f('ix_standard_relationships_target_standard_id'), table_name='standard_relationships')
    op.drop_index(op.f('ix_standard_relationships_source_standard_id'), table_name='standard_relationships')
    op.drop_index('ix_standard_relationships_pair', table_name='standard_relationships')
    op.drop_table('standard_relationships')
    op.drop_index(op.f('ix_standard_designations_standard_id'), table_name='standard_designations')
    op.drop_index(op.f('ix_standard_designations_normalised'), table_name='standard_designations')
    op.drop_index(op.f('ix_standard_designations_designation'), table_name='standard_designations')
    op.drop_table('standard_designations')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_expiry', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_material_records_split_category', table_name='material_records')
    op.drop_index(op.f('ix_material_records_split'), table_name='material_records')
    op.drop_index(op.f('ix_material_records_source_record_id'), table_name='material_records')
    op.drop_index('ix_material_records_plant', table_name='material_records')
    op.drop_index(op.f('ix_material_records_legacy_code'), table_name='material_records')
    op.drop_index('ix_material_records_cpse_legacy', table_name='material_records')
    op.drop_index(op.f('ix_material_records_cpse_id'), table_name='material_records')
    op.drop_index(op.f('ix_material_records_cluster_id'), table_name='material_records')
    op.drop_index(op.f('ix_material_records_category'), table_name='material_records')
    op.drop_table('material_records')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_at_action', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standards_family'), table_name='standards')
    op.drop_index(op.f('ix_standards_code'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_plants_cpse_id'), table_name='plants')
    op.drop_index('ix_plants_cpse_code', table_name='plants')
    op.drop_table('plants')
    op.drop_table('standard_sources')
    op.drop_index(op.f('ix_engine_runs_split'), table_name='engine_runs')
    op.drop_table('engine_runs')
    op.drop_index(op.f('ix_cpses_code'), table_name='cpses')
    op.drop_table('cpses')
    # ### end Alembic commands ###
